baseurl                = "https://ericaxia.github.io/"
theme = "mytheme"

archetypeDir           = "archetypes"
author                 = "admin"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
title                  = "Erica Xia"
enableEmoji            = true
DefaultContentLanguage = "en"
#disqusShortname        = ""


[Languages]
[Languages.en]
weight = 1

[blackfriday]
angledQuotes = true
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true
plainIDAnchors = true
extensions = [
	"hardLineBreak", # newlines result in line breaks
]

[markup.goldmark.renderer]
hardWraps = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  search_engine = false
  #google_analytics_id = ""
  twitter_username = "username"
  paginate = 5
