theme = "hugo_theme_pickles"
baseurl = "/"
languageCode = "en-us"
Title = "Erica Xia"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2020"

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  custom_css = ["/css/custom.css"]

  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "Your Twitter username"
  github = "EricaXia"
  youtube = "Your YouTube username"
  linkedin = "erica-xia-9370aa9a"
  medium = "Your Medium username"
  # Disqus shortname
  disqus = ""
  author = "Erica Xia"
  authorwebsite = "example.com"
  avatar = "/path/to/avatar"
  contact = "mailto:ericaxia@usc.edu"
  bio = ""

  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Data Science graduate student @ USC."

  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[[menu.main]]
    name = "Github"
    url = "/tags"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/tags"
    weight = 6


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
